### ISSUE TITLE
Mac builds missing Vulkan

### ISSUE THREAD

**Issue by CitricDolphin1** [BlackMIDIDevs/wasabi#86]
Mac builds of this app are dependent on Vulkan but do not seem to have been built with the necessary Vulkan libraries. It searches for a Vulkan dylib in four locations, and all four of these locations do not accurately reflect the location of Vulkan libraries on a Mac system with the Vulkan SDK installed.

Attempting to launch the program prints this error to the terminal and then terminates the program.

```
thread 'main' panicked at src/renderer.rs:45:44:
called `Result::unwrap()` on an `Err` value: LibraryLoadFailure(DlOpen { desc: "dlopen(libvulkan.1.dylib, 0x0005): tried: \'libvulkan.1.dylib\' (no such file), \'/System/Volumes/Preboot/Cryptexes/OSlibvulkan.1.dylib\' (no such file), \'/usr/lib/libvulkan.1.dylib\' (no such file, not in dyld cache), \'libvulkan.1.dylib\' (no such file)" })
```

**Comment by Kaydax** [comment]
Mac does not support Vulkan. You have to use MoltenVK in order to use Vulkan on Mac systems. But the other problem lies in the fact that MoltenVK currently does not support compute / geometry shaders, which is needed for Wasabi to function. The mac build that are there are considered unsupported and will soon be removed until MoltenVK properly supports compute / geometry shaders
